[platformio]
src_dir = main

; Общие настройки для всех чипов
[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21-2/platform-espressif32.zip
framework = espidf
monitor_speed = 115200
; board_build.partitions = partitions.csv ; Общий файл разделов (важно для Matter)

; --- Конфигурации для ESP32-S3 ---

[env:s3]
board = esp32-s3-devkitc-1
board_build.cmake_extra_args = 
    -D SDKCONFIG_DEFAULTS="config/sdkconfig.defaults;config/sdkconfig.defaults.esp32s3"
 
[env:s3_mqtt]
extends = env:s3
custom_rsd_integration = "mqtt"
board_build.cmake_extra_args = 
    -D RSD_USE_WIFI=1
    -D SDKCONFIG_DEFAULTS="config/sdkconfig.defaults;config/sdkconfig.defaults.esp32s3;config/sdkconfig.mqtt"

[env:s3_matter_wifi]
extends = env:s3
custom_rsd_integration = "matter"
board_build.cmake_extra_args = 
    -D RSD_USE_WIFI=1
    -D SDKCONFIG_DEFAULTS="config/sdkconfig.defaults;config/sdkconfig.defaults.esp32s3;config/sdkconfig.matter"

; --- Конфигурации для ESP32-H2 ---

; [env:h2_zigbee]
; board = esp32-h2-devkitm-1
; build_flags = 
;     -D USE_ZIGBEE
;     -D SOC_IEEE802154_SUPPORTED=1

; [env:h2_matter_thread]
; board = esp32-h2-devkitm-1
; build_flags = 
;     -D USE_MATTER
;     -D MATTER_OVER_THREAD
